name: sqfly
version: 1.0.0-alpha.1
homepage: https://github.com/hsul4n/dart-sqfly
description: Simple ORM inspired from ActiveRecord, built ontop of Sqflite and uses DAO architecture.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^1.3.1
  sqflite_common: ^1.0.2+1
  colorize: ^2.0.0
  core_extension: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
